name: bedrock
description: "A minimalist, privacy-first, offline notes and task manager."
publish_to: 'none'
version: 2.4.1+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  fl_chart: ^0.70.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/Design/
    - assets/bedrock_minimalist_logo.png

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/bedrock_minimalist_logo.png"

